server:
  port: 9006
spring:
  application:
    name: blog-apit


  data:
    mongodb:
      host: 192.168.1.107
      port: 27017
      database: blog
      username: root

  redis:
    host: 192.168.1.107
    port: 6379
    password: 123456
