server: 
  port: 9004
spring: 
  application:  
    name: blog_article #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.94.10.48:3306/tensquare_article?characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true

  redis:
    host: 192.168.1.107
    port: 6379
    password: 123456


