server:
  port: 9002

spring:
  application:
  ##  中间只能是横杠，不能使用下划线
    name: blog_recruit
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.94.10.48:3306/tensquare_recruit?characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true

