server: 
  port: 9008
spring: 
  application:  
    name: blog_user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.94.***.48:3306/tensquare_user?characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true

  redis:
    host: 192.168.1.107
    port: 6379
    password: 123456

  rabbitmq:
    host: 192.168.1.107
    port: 5672
    username: root
    password: 123456

aliyun:
  sms:
    accessKeyId: LTAI4Fu***KCQ8VU
    accessKeySecret: VmyRFbN***2SPAAcrftz
    template_code: SMS_1***15157
    sign_name: Albert博客

## jwt 认证配置
jwt:
  config:
    key: dongl
    time: 3600000
