server:
  port: 12000

spring:
  application:
    name: blog-config

  cloud:
    config:
      server:
        git:
          uri: https://github.com/SoftCancer/SpringcloudConfig.git
          search-paths: blog

  ## 启动服务直接访问;http://localhost:12000/blog-base-dev.yml



